# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mymoip"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Irio Irineu Musskopf Junior"]
  s.date = "2012-10-18"
  s.description = "Provides a implementation of MoIP's transparent checkout."
  s.email = "irio.musskopf@caixadeideias.com.br"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/mymoip.rb",
    "lib/mymoip/credit_card.rb",
    "lib/mymoip/credit_card_payment.rb",
    "lib/mymoip/instruction.rb",
    "lib/mymoip/json_parser.rb",
    "lib/mymoip/payer.rb",
    "lib/mymoip/request.rb",
    "lib/mymoip/requests/payment_request.rb",
    "lib/mymoip/requests/transparent_request.rb",
    "mymoip.gemspec",
    "test/fixture.rb",
    "test/helper.rb",
    "test/test_credit_card_payment.rb",
    "test/test_creditcard.rb",
    "test/test_instruction.rb",
    "test/test_mymoip.rb",
    "test/test_payer.rb",
    "test/test_payment_request.rb",
    "test/test_request.rb",
    "test/test_transparent_request.rb"
  ]
  s.homepage = "http://github.com/Irio/mymoip"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "MoIP transactions in a gem to call your own."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<turn>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<turn>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<turn>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

